import type { Vehicle } from "./types";

export const mockVehicles: Vehicle[] = [
  {
    id: "1",
    model: "VinFast VF 3",
    imageUrl: "/vf3.png",
    batteryLevel: 100,
    estimatedRange: 210,
    pricePerHour: 25,
    locationId: "1",
    isAvailable: true,
  },
  {
    id: "2",
    model: "VinFast VF 5",
    imageUrl: "/vf5.jpg",
    batteryLevel: 100,
    estimatedRange: 300,
    pricePerHour: 35,
    locationId: "1",
    isAvailable: true,
  },
  {
    id: "3",
    model: "VinFast VF 6",
    imageUrl: "/vf6-plus.jpg",
    batteryLevel: 100,
    estimatedRange: 460,
    pricePerHour: 52,
    locationId: "1",
    isAvailable: true,
  },
  {
    id: "4",
    model: "VinFast VF 7",
    imageUrl: "/vf7.jpg",
    batteryLevel: 100,
    estimatedRange: 490,
    pricePerHour: 70,
    locationId: "1",
    isAvailable: true,
  },
  {
    id: "5",
    model: "VinFast VF 8",
    imageUrl: "/vf8.jpg",
    batteryLevel: 100,
    estimatedRange: 470,
    pricePerHour: 70,
    locationId: "1",
    isAvailable: true,
  },
  {
    id: "6",
    model: "VinFast VF 9",
    imageUrl: "/vf9.jpg",
    batteryLevel: 100,
    estimatedRange: 580,
    pricePerHour: 110,
    locationId: "1",
    isAvailable: true,
  },
];
